ALTER TABLE t_transaction_data
ADD COLUMN flg_prcs CHAR(1) DEFAULT '0',
ADD COLUMN rcode VARCHAR(4),
ADD COLUMN rcmsg VARCHAR(70),
ADD COLUMN created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN tsflging TIMESTAMP,
ADD COLUMN appsrvs VARCHAR(10);