/* >>>> SP_TXMULTI_INQ BY EKGUN 12.09.2024 >>>>
 * CALL MASTER.SP_TXMULTI_INQ( ?, '010', '093602328993', '360', ?, ?, ?, ?  );
 * */
 /* WARNING ! REMOVE ON RELEASE  
    
	CALL MASTER.SP_TXMULTI_INQ( ?, '010', '2320609', '360', ?, ?, ?, ?, ?  ); 
	CALL MASTER.SP_TXMULTI_INQ( ?, '009', '0102000111', '360', ?, ?, ?, ?, ?  ); 
	CALL MASTER.SP_TXMULTI_INQ( ?, '010', '0151018719', '840', ?, ?, ?, ?, ?  ); 
	CALL MASTER.SP_TXMULTI_INQ( ?, '014', '010121000043', '360', ?, ?, ?, ?, ?  ); 
	CALL MASTER.SP_TXMULTI_INQ( ?, '014', '016863532402', '360', ?, ?, ?, ?, ?  ); 
	CALL MASTER.SP_TXMULTI_INQ( ?, '010', '0250000103', '840', ?, ?, ?, ?, ?  ); 
	CALL MASTER.SP_TXMULTI_INQ( ?, '010', '0200011964', '360', ?, ?, ?, ?, ?  ); 
	CALL MASTER.SP_TXMULTI_INQ( ?, '010', '093602328994', '360', ?, ?, ?, ?, ?  );
	CALL MASTER.SP_TXMULTI_INQ( ?, '054', '098402320001', '840', ?, ?, ?, ?, ?  );
 */

CREATE OR REPLACE PROCEDURE MASTER.SP_TXMULTI_INQ ( 
	OUT STATUS DOUBLE PRECISION , 
	IN TX_KDCAB CHAR(3) , 
	IN TX_NOREK VARCHAR(12) , 
	IN TX_KDVAL CHAR(3) , 
	OUT TX_SALDOAKHIR DECIMAL(15, 2) , 
	OUT TX_GSSLINDUK CHAR(7) , 
	OUT TX_KDAPL CHAR(2) ,
	OUT TX_PESAN VARCHAR(255) , 
	OUT OC_RCODE CHAR(2) ) 
	LANGUAGE SQL 
	SPECIFIC MASTER.SP_TXMULTI_INQ 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CS , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
	DECLARE V_VALUTA		CHAR ( 3 ) ; 
	DECLARE SQLCODE INT DEFAULT 0 ; 
	DECLARE LC_KD_PRODUK CHAR ( 2 ) DEFAULT '' ; 
	DECLARE V_KD_STATUS CHAR ( 1 ) ;
	 
	SET STATUS = 0 ;
	
	IF LENGTH(TX_NOREK) = 7 THEN 
		SET TX_KDAPL = '00' ;
	ELSE
		SET TX_KDAPL = LEFT ( TX_NOREK , 2 ) ;
	END IF ;
	 
	CASE TX_KDAPL 
		WHEN '00' THEN 
			SELECT SALDO_AKHIR ,	KD_VALUTA 
			INTO   TX_SALDOAKHIR ,	V_VALUTA 
			FROM   MASTER . SSLEDGER_MASTER 
			WHERE  ( KD_CAB = TX_KDCAB ) AND ( NO_GSSL = TX_NOREK ) AND ( KD_VALUTA = TX_KDVAL ) ; 
			 
			IF SQLCODE <> 0 THEN 
				SET TX_PESAN = 'NO. REKENING PEMBUKUAN SALAH ' || TX_KDCAB || '-' || TX_NOREK || '-' || TX_KDVAL ; 
				SET STATUS = - 1 ; 
				SET OC_RCODE = '76' ; 
				GOTO AKHIR ; 
			END IF ; 
			 
		WHEN '01' THEN 
			 -- GET SALDO AKHIR 
			SELECT SALDO_AKHIR ,	KD_VALUTA , KD_PRODUK , KD_STATUS
			INTO   TX_SALDOAKHIR ,	V_VALUTA ,	LC_KD_PRODUK , V_KD_STATUS
			FROM   MASTER . GIRO_MASTER 
			WHERE  ( KD_CAB = TX_KDCAB ) AND ( NO_REK = TX_NOREK ) AND ( KD_VALUTA = TX_KDVAL ) ; 
			 
			IF SQLCODE <> 0 THEN 
				SET TX_PESAN = 'NO. REKENING GIRO SALAH ' || TX_KDCAB || '-' || TX_NOREK ; 
				SET STATUS = - 1 ; 
				SET OC_RCODE = '76' ; 
				GOTO AKHIR ; 
			END IF ; 	

			IF V_KD_STATUS = '9' THEN 
				SET TX_PESAN = 'NO. REK SUDAH TUTUP ! ' || TX_KDCAB || '-' || TX_NOREK ; 
				SET STATUS = - 1 ; 
				SET OC_RCODE = '78' ; 
				GOTO AKHIR ; 
			END IF ;			
			 
			 --GET NO_GSSL INDUK 
			SELECT	NO_GSSL 
			INTO	TX_GSSLINDUK 
			FROM	MASTER . TBL_PRD_GIRO 
			WHERE	KD_PRODUK = LC_KD_PRODUK 
			AND		KD_VALUTA = V_VALUTA ; 
			 
			IF SQLCODE <> 0 THEN 
				SET TX_PESAN = 'INDUK GIRO TIDAK TERDAFTAR ' || TX_KDCAB || '-' || TX_NOREK ; 
				SET STATUS = - 1 ; 
				SET OC_RCODE = '96' ; 
				GOTO AKHIR ; 
			END IF ; 
			 
		WHEN '02' THEN 
			 -- GET SALDO AKHIR 
			SELECT SALDO_AKHIR ,	KD_VALUTA , KD_PRODUK ,    KD_STATUS
			INTO   TX_SALDOAKHIR ,	V_VALUTA ,	LC_KD_PRODUK , V_KD_STATUS
			FROM   MASTER . SAVE_MASTER 
			WHERE ( KD_CAB = TX_KDCAB ) AND ( NO_REK = TX_NOREK ) AND ( KD_VALUTA = TX_KDVAL ) ; 
			 
			IF SQLCODE <> 0 THEN 
				SET TX_PESAN = 'NO. REKENING TABUNGAN SALAH ' || TX_KDCAB || '-' || TX_NOREK ; 
				SET STATUS = - 1 ; 
				SET OC_RCODE = '76' ; 
				GOTO AKHIR ; 
			END IF ; 
  
			IF V_KD_STATUS = '9' THEN 
				SET TX_PESAN = 'NO. REK SUDAH TUTUP ! ' || TX_KDCAB || '-' || TX_NOREK ; 
				SET STATUS = - 1 ; 
				SET OC_RCODE = '78' ; 
				GOTO AKHIR ; 
			END IF ;
			 
			 --GET NO_GSSL INDUK 
			SELECT	NO_GSSL 
			INTO	TX_GSSLINDUK 
			FROM	MASTER . TBL_PRD_SAVE 
			WHERE	KD_PRODUK = LC_KD_PRODUK 
			AND		KD_VALUTA = V_VALUTA ; 
			 
			IF SQLCODE <> 0 THEN 
				SET TX_PESAN = 'INDUK TABUNGAN TIDAK TERDAFTAR ' || TX_KDCAB || '-' || TX_NOREK ; 
				SET STATUS = - 1 ; 
				SET OC_RCODE = '96' ; 
				GOTO AKHIR ; 
			END IF ; 
			 
		WHEN '09' THEN 
				SELECT SALDO_AKHIR ,		NO_GSSL ,		KD_VALUTA 
				INTO TX_SALDOAKHIR ,		TX_GSSLINDUK ,	V_VALUTA 
				FROM MASTER . NOMI_MASTER 
				WHERE ( KD_CAB = TX_KDCAB ) AND ( NO_REK = TX_NOREK ) AND	( KD_VALUTA = TX_KDVAL ) ;	 
			 
			IF SQLCODE <> 0 THEN 
				SET TX_PESAN = 'NO. REKENING NOMINATIF PEMBUKUAN SALAH !' || TX_KDCAB || '-' || TX_NOREK || '-' || TX_KDVAL ; 
				SET STATUS = - 1 ; 
				SET OC_RCODE = '76' ; 
				GOTO AKHIR ; 
			END IF ;				 
  
		ELSE 
			SET TX_PESAN = 'NO. REKENING SALAH ' || TX_KDCAB || '-' || TX_NOREK || '-' || TX_KDVAL ; 
			SET STATUS = - 1 ; 
			SET OC_RCODE = '76' ; 
			GOTO AKHIR ; 
		END CASE ;	 
  
		AKHIR : 
			IF STATUS = 0 THEN 
				SET OC_RCODE = '00' ;
				SET TX_PESAN = 'NO. REKENING VALID' ;
			END IF ; 
	END  ; 
  
