/* TESTING ONLY Edited by Ekgun 2024.10.22 */
-- CALL >> SP_TXMULTI_INSERT ( IVC_JNSTX, IC_KDVIA, IVC_NOARSIP, IC_LOKTX, IC_KDVAL, IVC_DB, IVC_KR, IVC_APP, OC_RCODE, OVC_PESAN )
-- EXP  >> SP_TXMULTI_INSERT ( 'BPJS_TK_PU', 'IBB', 'IB01364889', '010', '360', '6000.00', '4488.00|1236.00|276.00|0.00|0.00', 'IGATE', '', '' )

-- CALL MASTER.SP_TXMULTI_INSERT( ?, '010', '00', '2320609', '360', ?, ?, ?, ?  ); 

/* == CHANGE LOG ==
   @01 2024.10.18 - Init Store Procedure
*/

/* SP_TXMULTI_INSERT BY EKGUN 12.09.2024 */
CREATE OR REPLACE PROCEDURE MASTER.SP_TXMULTI_INSERT ( 
	OUT ODO_STATUS 		DOUBLE PRECISION , 	
	-- HEADER	
	IN IVC_JNSTX 		VARCHAR( 50 ) ,
	IN IC_KDVIA 		CHAR ( 3 ) ,
	IN IVC_REFNO		VARCHAR ( 30 ) ,
	IN IVC_NOARSIP 		CHAR ( 10 ) ,
	IN IC_LOKTX 		CHAR ( 3 ) ,
	IN IC_KDVAL 		CHAR ( 3 ) ,
	IN IVC_DB 			VARCHAR ( 32000 ) ,
	IN IVC_KR 			VARCHAR ( 32000 ) ,
	IN IC_APP 			CHAR ( 5 ) ,
	IN IC_PROCBY 		CHAR ( 1 ) ,
	IN IC_TGLSYS		CHAR ( 8 ) ,
	IN IC_JAMTX 		CHAR ( 6 ) ,
	IN IC_FLGKOR		CHAR ( 1 ) , 
    IN IVC_ADDINFO      VARCHAR ( 1024 ) ,	
	-- RESPON	 
	OUT OC_RCODE 		CHAR(2) , 
	OUT OVC_PESAN 		VARCHAR(255)	
    ) 
	LANGUAGE SQL 
	SPECIFIC MASTER.SP_TXMULTI_INSERT 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *CS , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	
	P1 : BEGIN 
	DECLARE SQLCODE INT DEFAULT 0 ; 
	DECLARE LD_OPENDATE DATE ; 
	DECLARE LC_LIB CHAR ( 1 ) ; 
	DECLARE LVC_LIBNAME VARCHAR ( 10 ) ;
	DECLARE LI_CNTDB INT DEFAULT 0 ;
	DECLARE LI_CPRMDB INT DEFAULT 0 ;
	DECLARE LI_CNTKR INT DEFAULT 0 ;
	DECLARE LI_CPRMKR INT DEFAULT 0 ;
	DECLARE LI_RTOT  INT DEFAULT 0 ;
	DECLARE LI_CURDATA INT DEFAULT 0 ;
	DECLARE LI_CURREV INT DEFAULT 0 ;
	DECLARE LDEC_SALDOAKHIR DECIMAL ( 17,2 ) DEFAULT 0 ;
	DECLARE LDEC_AKMDB DECIMAL ( 17,2 ) DEFAULT 0 ;
	DECLARE LDEC_AKMKR DECIMAL ( 17,2 ) DEFAULT 0 ;
	DECLARE LVC_KETLAIN2 VARCHAR ( 255 ) ;
	DECLARE LC_GSSLINDUK CHAR ( 8 ) ;
	DECLARE OVC_REFNO VARCHAR ( 30 ) ;
	DECLARE LC_BOLEHTX VARCHAR ( 10 ) ;
	
	-- PARAM ON LOOP
	DECLARE LC_DBKR CHAR( 1 ) ;
	DECLARE LC_DBKR_TMP CHAR ( 1 ) ;
	DECLARE LI_RNO INT DEFAULT 0 ;
	DECLARE LDEC_NOMINAL DECIMAL ( 17 , 2 ) DEFAULT 0 ;
	DECLARE LC_PREFX VARCHAR ( 30 ) ;
	DECLARE LC_KDCAB 	CHAR ( 3 ) ;
	DECLARE LC_KDAPL 	CHAR ( 2 ) ;
	DECLARE LVC_NOREK 	VARCHAR ( 12 ) ;
	DECLARE LVC_KETTX 	VARCHAR ( 120 ) ;
	DECLARE at_end INTEGER DEFAULT 0;
    DECLARE not_found CONDITION FOR SQLSTATE '02000';

	-- ======== MAIN CURSOR ========
	-- START #MAIN
  	DECLARE c1 CURSOR FOR 
	SELECT Z.DBKR, Z.KDCAB, Z.NOREK, Z.NOMINAL, Z.PREFX, 
	       ROW_NUMBER() OVER() AS RNO, COUNT(Z.RNO) OVER() AS RTOT
	FROM (
			SELECT  Y.DBKR, Y.RNO, Y.KDCAB, Y.NOREK, X.NOMINAL, Y.PREFX
			FROM    TABLE(MASTER.FN_SPLIT_NUM(IVC_DB, '|')) X,
					MASTER.PRM_TX_SPLIT Y
			WHERE   X.ID      = Y.RNO
			AND     Y.JNSTX   = IVC_JNSTX 
			AND     Y.KDVIA   = IC_KDVIA
			AND     Y.KDVAL   = IC_KDVAL
			AND     Y.KDSTS   = '1'
			AND     Y.DBKR    = 'D'
			AND     X.NOMINAL > 0
			UNION   ALL
			SELECT  Y.DBKR, Y.RNO, Y.KDCAB, Y.NOREK, X.NOMINAL, Y.PREFX
			FROM    TABLE(MASTER.FN_SPLIT_NUM(IVC_KR, '|')) X,
					MASTER.PRM_TX_SPLIT Y
			WHERE   X.ID      = Y.RNO
			AND     Y.JNSTX   = IVC_JNSTX
			AND     Y.KDVIA   = IC_KDVIA
			AND     Y.KDVAL   = IC_KDVAL
			AND     Y.KDSTS   = '1'
			AND     Y.DBKR    = 'K'
			AND     X.NOMINAL > 0 
		) Z ;
	
	DECLARE CONTINUE HANDLER FOR not_found SET at_end = 1;

	DECLARE EXIT HANDLER FOR SQLEXCEPTION , SQLWARNING 
		BEGIN 
			GET DIAGNOSTICS EXCEPTION 1 OVC_PESAN = MESSAGE_TEXT ; 
			SET ODO_STATUS = - 1 ; 
			SET OC_RCODE   = '99' ;
			ROLLBACK ; 				 
		END ; 
		
	-- END #MAIN
	
	-- ======== PARAM AND DEFAULT ========
	-- SET DEFAULT VALUE
	SET OVC_PESAN          = '' ; 
	SET ODO_STATUS         = - 1 ; 
	SET OC_RCODE           = '' ;
	SET LC_LIB             = '0' ; 
  		
	-- SET OPENDATE DAN LIBRARY AKTIF 
	SELECT OPEN_DATE 	, FLG_ATM , 
		   CASE WHEN FLG_ATM = '0' THEN 'MASTER' 
		        WHEN FLG_ATM = '1' THEN 'TEMPO' 
				ELSE 'INVALID' END
	INTO   LD_OPENDATE  , LC_LIB  , 
		   LVC_LIBNAME
	FROM   MASTER . SYSTEM_HOST ; 
	
	-- ======== VALIDASI ========
	-- CEK BOLEH TX
	SELECT  VALUE AS VAL 
	INTO    LC_BOLEHTX
	FROM    MASTER.TBL_PARAMETER 
	WHERE   KD_PARAM1 = '27' AND KD_PARAM2 = '01';
	
	IF LC_BOLEHTX IS NULL THEN 
		SET OVC_PESAN  = 'PARAMETER BOLEH-TX PARAM:27-01 TIDAK TERDAFTAR!' ; 
		SET ODO_STATUS = - 1 ; 
		SET OC_RCODE   = '88' ; 
		GOTO AKHIR ; 
	END IF ; 	
	
	IF LC_BOLEHTX != '1' THEN 
		SET OVC_PESAN  = 'TIDAK BOLEH TRANSAKSI!' ; 
		SET ODO_STATUS = - 1 ; 
		SET OC_RCODE   = '89' ; 
		GOTO AKHIR ;
	END IF ;
	
	-- CEK BALANCE (B) #B
	SELECT  COUNT ( ID ) AS CNTDB , SUM ( NOMINAL ) AS AKMDB
	INTO    LI_CNTDB              , LDEC_AKMDB
	FROM    TABLE ( MASTER.FN_SPLIT_NUM ( IVC_DB , '|' ) ) ;
	-- 
	SELECT  COUNT ( ID ) AS CNTKR , SUM ( NOMINAL ) AS AKMKR
	INTO    LI_CNTKR              , LDEC_AKMKR
	FROM    TABLE ( MASTER.FN_SPLIT_NUM ( IVC_KR , '|' ) ) ;

	IF LDEC_AKMDB != LDEC_AKMKR THEN
		SET OVC_PESAN   = 'AKUMULASI TRANSAKSI DEBET DAN KREDIT TIDAK BALANCE!' ; 
		SET OC_RCODE    = '90' ; 
		SET ODO_STATUS  = -1 ; 
		GOTO AKHIR ; 
	END IF ;

	-- CEK PARM TX SPLIT
	SELECT  COALESCE ( SUM ( CASE WHEN DBKR = 'D' THEN 1 ELSE 0 END ) , 0 ) AS DB, 
			COALESCE ( SUM ( CASE WHEN DBKR = 'K' THEN 1 ELSE 0 END ) , 0 ) AS KR 
	INTO    LI_CPRMDB , LI_CPRMKR 
	FROM    MASTER.PRM_TX_SPLIT 
	WHERE   JNSTX = IVC_JNSTX
	AND     KDVIA = IC_KDVIA
	AND     KDVAL = IC_KDVAL 
	AND     KDSTS = '1' ;
	
	-- VALIDASI PARAM SUDAH ADA
	IF LI_CPRMDB = 0 OR LI_CPRMKR = 0 THEN 
		SET OVC_PESAN   = 'PARAMETER DB|KR TIDAK TERDAFTAR! JNSTX-KDVIA : ' || IVC_JNSTX || '-' || IC_KDVIA || '-' || IC_KDVAL  ; 
		SET OC_RCODE    = '91' ; 
		SET ODO_STATUS  = -1 ; 
		GOTO AKHIR ; 
	END IF ;
	

	-- VALIDASI VALUE IN VS PARAM DEBET 
	IF LI_CPRMDB != LI_CNTDB THEN
	 	SET OVC_PESAN   = 'PARAMETER TRX DEBET TIDAK SESUAI! V:' || LI_CNTDB || '-P:' || LI_CPRMDB ; 
	 	SET OC_RCODE    = '92' ; 
	 	SET ODO_STATUS  = -1 ; 
	 	GOTO AKHIR ;
	END IF ;

	-- VALIDASI VALUE IN VS PARAM KREDIT 
	IF LI_CPRMKR != LI_CNTKR THEN
	 	SET OVC_PESAN   = 'PARAMETER TRANSAKSI KREDIT TIDAK SESUAI! V:' || LI_CNTKR || '-P:' || LI_CPRMKR ; 
	 	SET OC_RCODE    = '93' ; 
	 	SET ODO_STATUS  = -1 ; 
	 	GOTO AKHIR ;
	END IF ;
	
	-- ======== LOOP DATA ========
	-- CEK DATA EXIST 
	SELECT  COUNT(RNO)
	INTO 	LI_CURDATA
	FROM    MASTER.TX_MULTIREK 
	WHERE   APP   = IC_APP 
	AND     REFNO = IVC_REFNO
	AND     TGLTX = LD_OPENDATE ;
	
	-- DATA EXIST
	IF LI_CURDATA >= 1 AND IC_FLGKOR = '0' THEN
	 	SET OVC_PESAN   = 'DATA SUDAH PERNAH DIKIRIM!' ; 
	 	SET OC_RCODE    = '94' ; 
	 	SET ODO_STATUS  = -1 ; 
	 	GOTO AKHIR ;
	END IF ;
	
	-- VALIDASI REVERSAL
	IF IC_FLGKOR = 'R' AND LI_CURDATA = 0 THEN 
		SET OVC_PESAN   = 'TRANSAKSI ORIGINAL TIDAK DITEMUKAN! '; 
	 	SET OC_RCODE    = '95' ; 
	 	SET ODO_STATUS  = -1 ; 
	 	GOTO AKHIR ;
	END IF ;  
	
	IF IC_FLGKOR = 'R' THEN 
		SELECT  COUNT(RNO)
		INTO 	LI_CURREV
		FROM    MASTER.TX_MULTIREK 
		WHERE   APP   = IC_APP 
		AND     REFNO = 'REV_' || IVC_REFNO
		AND     TGLTX = LD_OPENDATE ;
		
		IF LI_CURREV >= 1 THEN 
			SET OVC_PESAN   = 'TRANSAKSI SUDAH PERNAH DIREVERSAL! '; 
			SET OC_RCODE    = '96' ; 
			SET ODO_STATUS  = -1 ; 
			GOTO AKHIR ;
		END IF ;
		
	END IF ;
	
	
	-- CURSOR C1 LOOP DEBET / KREDIT
	OPEN c1; 
      fetch_loop: 
      LOOP 
        FETCH c1 INTO LC_DBKR_TMP , LC_KDCAB , LVC_NOREK , LDEC_NOMINAL, LC_PREFX , LI_RNO , LI_RTOT ;
			
			-- EXIT 
			IF at_end = 1 THEN
				LEAVE fetch_loop;
			END  IF;
		
			IF LC_KDCAB = '999' THEN 
			   SET LC_KDCAB = IC_LOKTX ;
			END IF ;
			
			-- INQUERY REKENING
			CALL MASTER.SP_TXMULTI_INQ ( ODO_STATUS , LC_KDCAB , LVC_NOREK , IC_KDVAL , LDEC_SALDOAKHIR , LC_GSSLINDUK , LC_KDAPL , OVC_PESAN , OC_RCODE  ); 
			
			-- INSERT TX_MULTIREK 
			IF OC_RCODE = '00' THEN 
			
				-- REVERSAL. REVERSE DB AND KR
				SET LC_DBKR   = LC_DBKR_TMP ;
				SET OVC_REFNO = IVC_REFNO ;
				IF IC_FLGKOR = 'R' THEN 
					
					IF LC_DBKR_TMP = 'D' THEN 
						SET LC_DBKR = 'K' ;
					ELSE
						SET LC_DBKR = 'D' ;
					END IF ;
					
					SET LC_PREFX     = 'REV' ;
					SET OVC_REFNO    = 'REV_' || IVC_REFNO ;
					SET LVC_KETLAIN2 = 'REVERSAL' ;
					
				END IF ;
				
				IF IVC_JNSTX = 'BPJS_TK_PU' THEN 
					SET LC_PREFX = 'PU' ;
				END IF ;	
					
			
				SET LVC_KETTX = LC_PREFX || ' ' ||  REPLACE(IVC_REFNO, '.', ' ') ||' ' || IVC_ADDINFO  ;
				
				INSERT INTO MASTER.TX_MULTIREK 	(	RNO			, RTOT			, RNOM			, APP		, 
													REFNO		, LOKTX			, KDCAB			, KDAPL		, 
													NOREK		, JUMTX			, DBKR			, KETTX		, 
													KDAUTO		, KDVALUTA		, TGLTX			, PROCBY	, 
													FLG			, NOARSIP
												) 
										VALUES  (	LI_RNO		, LI_RTOT		, LDEC_AKMKR	, IC_APP	, 
													OVC_REFNO	, IC_LOKTX		, LC_KDCAB		, LC_KDAPL	, 
													LVC_NOREK	, LDEC_NOMINAL	, LC_DBKR		, LVC_KETTX	, 
													'A'			, IC_KDVAL		, LD_OPENDATE	, 5 		, 
													0			, IVC_NOARSIP
												) ;
			ELSE 
			
			    -- INVALID. ROLLBACK INSERT
				ROLLBACK ; 				
				GOTO AKHIR ;
				LEAVE fetch_loop;
				
			END IF ;
        
      END LOOP fetch_loop;    

    CLOSE c1; 
	
	-- SUKSES
	SET OVC_PESAN = 'PROSES BERHASIL|' || LVC_LIBNAME || '|' || CHAR(LD_OPENDATE) ;
	
	-- END
	AKHIR :
	
	-- ======== LOGGING ========
	-- LOG
	INSERT INTO MASTER.TX_MULTIREK_LOG (  STATUS 		, REFNO 		 , APP 		,	KDVIA      ,
										  PROCBY 		, JNSTX  		 , RDB 		,   FLGATM     ,
										  RKR 			, AKMDB 		 , AKMKR 	,	IVCPAKET   ,
										  RTOT 			, RNOM 			 , KDVAL 	,
										  LOKTX 		, TGLTX			 , NOARSP 	,
										  RCODE 		, KETERANGAN	 , NOARSIP	,	
										  KETLAIN2 		, FLGKOR		 , TGLSYS	,
										  JAMTX 
										)
							VALUES		( ODO_STATUS	, OVC_REFNO 	 , IC_APP 		,  IC_KDVIA   ,
										  IC_PROCBY 	, IVC_JNSTX		 , LI_CNTDB 	,  LC_LIB     ,
										  LI_CNTKR		, LDEC_AKMDB	 , LDEC_AKMKR 	,  IVC_ADDINFO, -- aditional
										  LI_RTOT		, LDEC_AKMDB	 , IC_KDVAL 	,
										  IC_LOKTX		, LD_OPENDATE	 , IVC_NOARSIP 	,
										  OC_RCODE		, OVC_PESAN		 , ''			,
										  LVC_KETLAIN2 	, IC_FLGKOR		 , IC_TGLSYS    , 
										  IC_JAMTX
										);				 
	IF SQLCODE <> 0 THEN 
		SET OC_RCODE = '96' ; 
		 ROLLBACK ; 
	ELSE 
		COMMIT ; 
	END IF ;	 
	 
END P1  ; 

-- SAMPLE CALL >> NORMAL
/*
CALL MASTER.SP_TXMULTI_INSERT ( 
	? , 
	'BPJS_TK_PU' , 							-- JENIS TRANSAKSI / EBANKING PARAMETER
	'ATM' , 								-- KODE VIA TRX
	'BPJS_TK_PU.IB01364889' , 				-- NO. REFERENSI
	'IB01364889' , 							-- NO. ARSIP
	'010' , 							    -- KDCAB LOKTX
	'360' , 								-- KD VALUTA
	'6000.00', 								-- LIST TRX DB
	'4488.00|1236.00|276.00|0.00|0.00' , 	-- LIST TRX KR
	'IGATE' , 								-- APP CALLER
	'5' , 									-- PROCCESS BY 1/TELLE 3/EOD 5/SERVICES
	'20240913' ,							-- TANGGAL SYSTEM (CALLER) YYYYMMDD
	'235959' , 								-- JAM SYSTEM 
	'0' ,									-- 0/NORMAL R/REVERSAL
	? , 
	? );
	*/

-- SAMPLE CALL KOREKSI								
/* CALL MASTER.SP_TXMULTI_INSERT ( 
	? , 
	'BPJS_TK_PU' , 							-- JENIS TRANSAKSI / EBANKING PARAMETER
	'ATM' , 								-- KODE VIA TRX
	'BPJS_TK_PU.IB01364889' , 				-- NO. REFERENSI
	'IB01364889' , 							-- NO. ARSIP
	'010' , 							    -- KDCAB LOKTX
	'360' , 								-- KD VALUTA
	'6000.00', 								-- LIST TRX DB
	'4488.00|1236.00|276.00|0.00|0.00' , 	-- LIST TRX KR
	'IGATE' , 								-- APP CALLER
	'5' , 									-- PROCCESS BY 1/TELLE 3/EOD 5/SERVICES
	'20240913' ,							-- TANGGAL SYSTEM (CALLER) YYYYMMDD
	'235959' , 								-- JAM SYSTEM 
	'R' ,									-- 0/NORMAL R/REVERSAL
	? , 
	? ); 
*/

