-- Tabel ini digunakan untuk melakukan split jurnal via backend services jurnal multi

CREATE TABLE MASTER.TX_MULTIREK_LOG ( 
	STATUS DOUBLE PRECISION , 
	REFNO VARCHAR(30) , 
	APP VARCHAR(5) , 
	KDVIA CHAR(3) , 
	PROCBY CHAR(1) , 
	JNSTX VARCHAR(30) , 
	RDB INTEGER , 
	RKR INTEGER , 
	AKMDB DECIMAL(17, 2) , 
	AKMKR DECIMAL(17, 2) , 
	RTOT INTEGER , 
	RNOM DECIMAL(17, 2) , 
	KDVAL CHAR(3) , 
	LOKTX CHAR(3) , 
	TGLTX DATE , 
	NOARSP VARCHAR(10) , 
	RCODE CHAR(2) , 
	KETERANGAN VARCHAR(100) , 
	NOARSIP VARCHAR(10) NOT NULL DEFAULT '' , 
	KETLAIN2 VARCHAR(255) , 
	FLGATM CHAR(1) , 
	FLGKOR CHAR(1) , 
	TGLSYS CHAR(8) , 
	JAMTX CHAR(6) , 
	IVCPAKET VARCHAR(1024) , 
	TSINSERT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	NEWKEY SMALLINT GENERATED ALWAYS AS IDENTITY ( 
	START WITH 1 INCREMENT BY 1 
	NO MINVALUE NO MAXVALUE 
	CYCLE NO ORDER 
	CACHE 20 ) 
	, 
	CONSTRAINT MASTER.TX_MULTIREK_LOG PRIMARY KEY( NEWKEY , TSINSERT ) )   
	;


-- DROP TABLE MASTER.PRM_TX_SPLIT ;
CREATE TABLE MASTER.PRM_TX_SPLIT (
	JNSTX		VARCHAR(30) 	NOT NULL ,			-- BPJS_TKPU 
	KDVIA		CHAR(3)			NOT NULL ,			-- REF: TTP REK NOMINAL
	RNO			INTEGER			NOT NULL ,			-- NO. URUTAN SEQ NUMBER
	DBKR		CHAR(1) 		NOT NULL ,			-- REF: D/DEBET K/KREDIT
	KDCAB		CHAR(3)			NOT NULL ,			-- REF: TBL_CABANG
	NOREK		VARCHAR(15) 	NOT NULL ,			-- REF: SSLEDGER, SAVE, GIRO, NOMI
	KDVAL		CHAR(3)			DEFAULT '360' , 	-- REF: TBL_VALUTA
	PREFX		VARCHAR(30)		NOT NULL ,			-- REF: INITIAN / PREFIX
	KDSTS 		CHAR(1)			DEFAULT '0' ,   	-- REF: 0/OFF 1/AKTIF
	KET			VARCHAR(100)	DEFAULT '-' ,		-- Keterangan 
	USRCRT		VARCHAR(5)		DEFAULT 'O0000' , 	-- KodeUser INPUT
	USRUPD		VARCHAR(5) ,						-- KodeUser UPDATE						
	TSCRT		TIMESTAMP 		DEFAULT CURRENT TIMESTAMP ,
	CONSTRAINT MASTER.PRM_TX_SPLIT PRIMARY KEY (JNSTX, KDVIA, DBKR, RNO, KDVAL)
);

-- INSERT Tabel Global Parm 
INSERT INTO MASTER.TBL_PARAMETER (KD_PARAM1, KD_PARAM2, KETERANGAN, VALUE) VALUES('27', '01', 'TXMULTI - ENGINE BOLEH TX  0|NO ; 1|YES', '1');

-- INSERT Tabel Parameter
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'IBB', 1, 'D', '999', '093602328993', '360', 'BPJS TK PU', '1', 'DB - TTP BPJS TK PU');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'IBB', 1, 'K', '999', '093602323219', '360', 'JHT', '1', 'KR - JHT');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'IBB', 2, 'K', '999', '093602323462', '360', 'JKK', '1', 'KR - JKK');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'IBB', 3, 'K', '999', '093602320944', '360', 'JKM', '1', 'KR - JKM');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'IBB', 4, 'K', '999', '093602320945', '360', 'JPK', '1', 'KR - JPK');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'IBB', 5, 'K', '999', '093602320946', '360', 'JPN', '1', 'KR - JPN');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'TLR', 1, 'D', '999', '093602323462', '360', 'BPJS TK PU', '1', 'DB - TTP BPJS TK PU');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'TLR', 1, 'K', '010', '0100012211', '360', 'JHT', '1', 'KR - JHT');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'TLR', 2, 'K', '010', '0100012257', '360', 'JKK', '1', 'KR - JKK');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'TLR', 3, 'K', '010', '0100012397', '360', 'JKM', '1', 'KR - JKM');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'TLR', 4, 'K', '010', '0100012622', '360', 'JPK', '1', 'KR - JPK');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'TLR', 5, 'K', '010', '0100012840', '360', 'JPN', '1', 'KR - JPN');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'MB ', 1, 'D', '999', '093602323462', '360', 'BPJS TK PU', '1', 'DB - TTP BPJS TK PU');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'MB ', 1, 'K', '010', '0100012211', '360', 'JHT', '1', 'KR - JHT');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'MB ', 2, 'K', '010', '0100012257', '360', 'JKK', '1', 'KR - JKK');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'MB ', 3, 'K', '010', '0100012397', '360', 'JKM', '1', 'KR - JKM');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'MB ', 4, 'K', '010', '0100012622', '360', 'JPK', '1', 'KR - JPK');
INSERT INTO MASTER.PRM_TX_SPLIT (JNSTX, KDVIA, RNO, DBKR, KDCAB, NOREK, KDVAL, PREFX, KDSTS, KET) VALUES('BPJS_TK_PU', 'MB ', 5, 'K', '010', '0100012840', '360', 'JPN', '1', 'KR - JPN');

SELECT * FROM master.PRM_TX_SPLIT ;   